#!/usr/bin/env zsh
# I am using zsh instead of bash.  I was having some troubles using bash with
# arrays.  Didn't want to investigate, so I just did zsh
DOTFILES=${DOTFILES:-"$HOME/.dotfiles/"}
STOW_FOLDERS=${STOW_FOLDERS:-"alacritty,bin,dunst,dwm,dwmblocks,lf,mpd,mpv,ncmpcpp,newsboat,nvim,picom,qtile,ranger,redshift,rofi,shell,wget,x11,zathura,zsh"}

for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Removing $folder"
    stow -D $folder -d "$DOTFILES"
done
