#!/bin/sh
#
#clean home directory
alias yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config"
alias irssi=irssi --config="$XDG_CONFIG_HOME"/irssi/config --home="$XDG_DATA_HOME"/irssi

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# navigation
alias ..='cd ..'

# Changing "ls" to "eza"
alias ls='eza --icons --color=auto --group-directories-first' # my preferred listing
alias la='eza --icons -ah --color=auto --group-directories-first'  # all files and dirs
alias ll='eza --icons -lah --color=auto --group-directories-first'  # long format
alias lt='eza --icons -aT --color=auto --group-directories-first' # tree listing
alias lm='eza --icons -ah --color=auto --sort=modified --group-directories-first'  # all files and dirs

alias l.='eza -a --icons| grep -E "^\."'

# confirm before overwriting something
alias cp="cp -iv"
alias mv='mv -iv'
alias rm='rm -I'

# mkdir recursively
alias mkdir='mkdir -vp'

#devour window swallowing
alias mpvd="devour mpv"
alias sxid="devour sxiv"
# allen
alias live="python ~/stuff/vid/test.py"

#I am a bit lazy
# alias please='sudo $(fc -ln -1)'
alias p='sudo pacman'
alias v='nvim'
alias SS='sudo systemctl'
alias c='xclip -selection clip'
alias bt='bluetoothctl'
alias ff='firefox-developer-edition'
alias sdh='sudo dhcpcd'


#???
alias mine='sudo /usr/bin/cpuminer -a cryptonight -o stratum+tcp://pool.minexmr.com:4444 -u `cat ~/mineid` -p x -t 3'
alias rice='nitrogen --save --set-scaled --random ~/wallpapers/ && python ~/.config/scripts/wallpaper_theme.py && qtile cmd-obj -o cmd -f restart'
alias spotify='LD_PRELOAD=/usr/lib/spotify-adblock.so spotify'
alias b='cd /mnt/winlinux/bpms'
alias l='cd /mnt/personal/Videos/'
alias wallchooser="find	"$HOME/wallpapers/"find /home/yogansh/wallpapers/ -name '*.png' -o -name '*.jpg' | sxiv -r -q -t -o -|xargs -r swaybg -m fill -i"
alias evg="sudo evtest --grab"
